[build]
builder = "nixpacks"
buildCommand = "cd scanner && npm install"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20"]

[deploy]
startCommand = "cd scanner && node scanner.js"
restartPolicyType = "always"
